name: Publicize Release

on:
  release:
    types: [published]

jobs:
  discord:
    name: "Discord Announcements"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Send discord announcement"
        env:
          repo_name: ${{ github.repository }} # Includes both owner name and repo name - requred for first curl
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |

          echo "Getting release information from '$tag'..."

          release_data=$(\
          curl -s                                                    \
          -H "Accept: application/vnd.github+json"                   \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}"      \
          -H "X-GitHub-Api-Version: 2022-11-28"                      \
          https://api.github.com/repos/$repo_name/releases/tags/$tag)

          body=$(jq ".body" <<< "$release_data")
          tag=$(jq ".tag_name" <<< "$release_data")
          url=$(jq ".html_url" <<< "$release_data")

          # Remove " from variable ends
          body="${body%\"}"
          body="${body#\"}"

          tag="${tag%\"}"
          tag="${tag#\"}"

          url="${url%\"}"
          url="${url#\"}"
          
          msg="# New Release - ${GITHUB_REPOSITORY#*/}\n-# $tag\n-----------\n$body\n\n-----------\nGithub link: $url\n||<@&1379694913586728991>||"

          curl -sSX POST ${{ secrets.DISCORD_ANNOUNCE_URL }}     \
          -H 'Content-Type: application/json'                    \
          -d "{\"content\":\"$msg\"}"
